/*
 * This Scala Testsuite was generated by the Gradle 'init' task.
 */
package PPS19.scalagram

import org.scalatest.funsuite.AnyFunSuite
import org.junit.runner.RunWith
import org.scalatestplus.junit.JUnitRunner

@RunWith(classOf[JUnitRunner])
class HelloWorldSuite extends AnyFunSuite {

  test("someLibraryMethod is always true") {
    def library = new HelloWorld()
    assert(library.someMethod())
  }

  /*test("requests library is working") {
    val r = requests.get("https://api.github.com/users/lihaoyi")
    assert(r.statusCode == 200)
  }*/
}
