/*
 * This Scala source file was generated by the Gradle 'init' task.
 */
package PPS19.scalagram

class HelloWorld {
  def someMethod(): Boolean = true
}

object HelloWorld extends App {
  println("Hello, world!")

  /*val r = requests.get("https://api.github.com/users/lihaoyi")

  println(r.statusCode)
  println(r.headers("content-type"))
  println(r.text)*/
}
