/*
 * This Scala source file was generated by the Gradle 'init' task.
 */
package PPS19.scalagram

class HelloWorld {
  def someMethod(): Boolean = true
}

object HelloWorld extends App {
  print("Hello, world!")
}
