# This workflow will build a Scala project with Gradle

name: Scala CI with Gradle

on:
  push:
  pull_request:
  schedule:
    - cron: "0 4 * * SUN"

jobs:
  preliminary-build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: Create application.properties file with the bot's token
        run: |
          mkdir -p src/main/resources
          echo token=${{secrets.BOT_TOKEN}} > src/main/resources/application.properties
      - name: Build with Gradle
        run: ./gradlew build

  build:
    needs: preliminary-build
    strategy:
      matrix:
        os: [ubuntu, macos, windows]
        java_version: [1.8, 11, 14]
    runs-on: ${{matrix.os}}-latest
    env:
      OS: ${{matrix.os}}
      JAVA_VERSION: ${{matrix.java_version}}
    steps:
      - name: Print OS
        run: echo ${{env.OS}}
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{matrix.java_version}}
      - name: Compile Scala
        run: ./gradlew compileScala
      - name: Compile Java
        run: ./gradlew compileJava
      - shell: bash
        run: OS=${{env.OS}}; JAVA=${{env.JAVA_VERSION}}; touch ${OS}_${JAVA};ls

  test:
    needs: build
    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        os: [ubuntu, macos, windows]
        java_version: [1.8, 11, 14]
    runs-on: ${{matrix.os}}-latest
    env:
      OS: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{matrix.java_version}}
      - name: Create application.properties file with the bot's token
        run: |
          mkdir -p src/main/resources
          echo token=${{secrets.BOT_TOKEN}} > src/main/resources/application.properties
      - name: Tests with Gradle
        run: ./gradlew test
