# This workflow will build a Scala project with Gradle

name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * SUN"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, windows, macos]
        java_version: [8, 11, 14]
    runs-on: ${{matrix.os}}-latest
    env:
      token-name: BOT_TOKEN_${{matrix.os}}_${{matrix.java_version}}
      log-test: test-${{matrix.os}}-${{matrix.java_version}}.log
      log-build: build-${{matrix.os}}-${{matrix.java_version}}.log
    steps:
      - uses: actions/checkout@v2
      - name: Create artifacts directories
        shell: bash
        run: |
          mkdir -p output/build
          mkdir -p output/test
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{matrix.java_version}}
      - name: Create application.properties file with the bot's token
        shell: bash
        run: |
          SECRET_VALUE=${{secrets[env.token-name]}}
          mkdir -p src/main/resources
          echo token=$SECRET_VALUE > src/main/resources/application.properties
      - name: Build with Gradle
        run: ./gradlew build -x test > output/build/${{env.log-build}}
      - name: Upload output errors as artifact if build has failed
        if: ${{failure()}}
        uses: actions/upload-artifact@v2
        with:
          name: buid-errors
          path: output/build/${{env.log-build}}
          retention-days: 14
      - name: Test (safe) with Gradle
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 10
          max_attempts: 2
          shell: bash
          command: ./gradlew test > output/test/${{env.log-test}}
      - name: Upload output errors as artifact if test has failed
        if: ${{failure()}}
        uses: actions/upload-artifact@v2
        with:
          name: test-errors
          path: output/test/${{env.log-test}}
          retention-days: 14
