# This workflow will build a Scala project with Gradle

name: Scala CI with Gradle

on:
  push:
  pull_request:
  schedule: 
    - cron: '0 4 * * SUN'

env: 
  OS: [ubuntu, macos, windows] 
  JAVA_VERSION: [1.8, 11, 14]

jobs:
  build:
    strategy:
      matrix:
        os: OS
    runs-on: ${{matrix.os}}-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14
    - name: Build with Gradle
      run: ./gradlew build