# This workflow will build a Scala project with Gradle

name: Scala CI with Gradle

on:
  push:
  pull_request:
  schedule:
    - cron: '0 4 * * SUN'

jobs:
  build:
    strategy:
      max-parallel: 2
      fail-fast: false
      matrix:
        os: [ubuntu]
        java_version: [11, 14]
    runs-on: ${{matrix.os}}-latest
    env:
      token-name: BOT_TOKEN_${{matrix.os}}_${{matrix.java_version}}
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: ${{matrix.java_version}}
    - name: Create application.properties file with the bot's token
      run: |
        echo "SECRET_NAME = $SECRET_NAME"
        echo "SECRET_NAME = ${{env.token-name}}"
        SECRET_VALUE=${{secrets[env.token-name]}}
        echo "SECRET_VALUE = $SECRET_VALUE"
        mkdir -p src/main/resources
        echo token=$SECRET_VALUE > src/main/resources/application.properties
    - name: Build with Gradle
      run: ./gradlew build