# This workflow will build a Scala project with Gradle

name: Scala CI with Gradle

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * SUN"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu]
        java_version: [11, 14]
    runs-on: ${{matrix.os}}-latest
    env:
      token-name: BOT_TOKEN_${{matrix.os}}_${{matrix.java_version}}
      log-name-test: test-${{matrix.os}}-${{matrix.java_version}}.log
      log-name-build: build-${{matrix.os}}-${{matrix.java_version}}.log
    steps:
      - uses: actions/checkout@v2
      - run: |
          mkdir -p output/build
          mkdir -p output/test
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{matrix.java_version}}
      - name: Create application.properties file with the bot's token
        shell: bash
        run: |
          SECRET_VALUE=${{secrets[env.token-name]}}
          mkdir -p src/main/resources
          echo token=$SECRET_VALUE > src/main/resources/application.properties
      - name: Build with Gradle
        run: ./gradlew build -x test > output/build/${{env.log-name-build}}
      - name: Test (safe) with Gradle
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 10
          max_attempts: 5
          shell: bash
          command: ./gradlew test > output/test/${{env.log-name-test}}
      - name: Upload output errors as Artifact
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: artifact-errors
          path: |
            output/test/${{env.log-name-test}}
            output/build/${{env.log-name-build}}
          retention-days: 5
