# This workflow will build a Scala project with Gradle

name: Scala CI with Gradle

on:
  push:
  pull_request:
  schedule:
    - cron: "0 4 * * SUN"

jobs:
  preliminary-build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: Create application.properties file with the bot's token
        run: |
          mkdir -p src/main/resources
          echo token=${{secrets.BOT_TOKEN}} > src/main/resources/application.properties
      - name: Build with Gradle
        run: ./gradlew build -x test
      - name: Gradle test
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 10
          max_attempts: 5
          shell: bash
          command: ./gradlew test

  build:
    needs: preliminary-build
    strategy:
      matrix:
        os: [ubuntu, macos, windows]
        java_version: [14, 12, 1.8]
    runs-on: ${{matrix.os}}-latest
    env:
      OS: ${{matrix.os}}
      JAVA_VERSION: ${{matrix.java_version}}
    steps:
      - name: Create application.properties file with the bot's token
        run: |
          mkdir -p src/main/resources
          echo token=${{secrets.BOT_TOKEN}} > src/main/resources/application.properties
      - name: Print OS
        run: echo ${{env.OS}}
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{matrix.java_version}}
      - name: Compile Scala source files
        shell: bash
        run: ./gradlew build -x test
      - name: Compile Scala test files
        shell: bash
        run: ./gradlew compileTestScala
      - name: Gradle test
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 10
          max_attempts: 20
          shell: bash
          command: ./gradlew test
