# This workflow will publish a GitHub release when an annotated pull request is made

name: Publish release

on:
  pull_request:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch:

jobs:
  publish_release:
    runs-on: ubuntu-latest
    env:
      MAVEN_CENTRAL_USERNAME: ${{secrets.MAVEN_CENTRAL_USERNAME}}
      MAVEN_CENTRAL_PASSWORD: ${{secrets.MAVEN_CENTRAL_PASSWORD}}
      ORG_GRADLE_PROJECT_signingKey: ${{secrets.ORG_GRADLE_PROJECT_SIGNINGKEY}}
      ORG_GRADLE_PROJECT_signingPassword: ${{secrets.ORG_GRADLE_PROJECT_SIGNINGPASSWORD}}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: Build with Gradle
        run: ./gradlew build
      - name: Create release
        uses: Roang-zero1/github-create-release-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Get latest tag
        uses: oprypin/find-latest-tag@v1
        with:
          repository: maciabit/PPS-19-scalagram
          releases-only: true
        id: tag_id
      - name: Load release artifact
        uses: Roang-zero1/github-upload-release-artifacts-action@master
        with:
          args: build/libs/PPS-19-scalagram-${{ steps.tag_id.outputs.tag }}.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish on Maven Central
        run: ./gradlew publishAllPublicationsToMavenCentralRepository
