# This workflow will publish a GitHub release when an annotated pull request is made

name: Publish release

on:
  pull_request:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  publish_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: ./gradlew build -x test
      - name: Create release
        uses: Roang-zero1/github-create-release-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Load release artifact
        uses: Roang-zero1/github-upload-release-artifacts-action@master
        with:
          args: build/libs/PPS-19-scalagram.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
