# This workflow will publish project's Jars on Maven Central

name: Publish Jars on Maven Central

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MAVEN_CENTRAL_USERNAME: ${{secrets.MAVEN_CENTRAL_USERNAME}}
      MAVEN_CENTRAL_PASSWORD: ${{secrets.MAVEN_CENTRAL_PASSWORD}}
      ORG_GRADLE_PROJECT_signingKey: ${{secrets.ORG_GRADLE_PROJECT_SIGNINGKEY}}
      ORG_GRADLE_PROJECT_signingPassword: ${{secrets.ORG_GRADLE_PROJECT_SIGNINGPASSWORD}}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: Create application.properties file with the bot's token
        shell: bash
        run: |
          mkdir -p src/main/resources
          echo token=hello > src/main/resources/application.properties
      - name: Build with Gradle
        run: ./gradlew build
      - name: Publish on Maven Central
        run: ./gradlew publishAllPublicationsToMavenCentralRepository
